// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhv7GkwP3pn35o1rGgtu3Ok3Vjhq67tcM',
    appId: '1:687380741071:web:520c92d9fae10aaad630ba',
    messagingSenderId: '687380741071',
    projectId: 'ims-89437',
    authDomain: 'ims-89437.firebaseapp.com',
    storageBucket: 'ims-89437.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhv7GkwP3pn35o1rGgtu3Ok3Vjhq67tcM',
    appId: '1:687380741071:android:520c92d9fae10aaad630ba',
    messagingSenderId: '687380741071',
    projectId: 'ims-89437',
    storageBucket: 'ims-89437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhv7GkwP3pn35o1rGgtu3Ok3Vjhq67tcM',
    appId: '1:687380741071:ios:520c92d9fae10aaad630ba',
    messagingSenderId: '687380741071',
    projectId: 'ims-89437',
    storageBucket: 'ims-89437.appspot.com',
    iosBundleId: 'com.example.ims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhv7GkwP3pn35o1rGgtu3Ok3Vjhq67tcM',
    appId: '1:687380741071:ios:520c92d9fae10aaad630ba',
    messagingSenderId: '687380741071',
    projectId: 'ims-89437',
    storageBucket: 'ims-89437.appspot.com',
    iosBundleId: 'com.example.ims',
  );
}
